<?php
/**
 * @file
 * Implements modifications to the webform submission process for Skateistan
 * intern/volunteer applications (two different webforms).
 */

function webform_skateistan_apps_webform_submission_insert($node, $submission) {
  if ($node->nid == 20) { // Intern application form
    _webform_skateistan_apps_submit_ia($node, $submission);
  }
  if ($node->nid == 33) { // Remote volunteer application form
    _webform_skateistan_apps_submit_rva($node, $submission);
  }
}

function _webform_skateistan_apps_hr_recipients() {
  return "hr@skateistan.org";
}

function _webform_skateistan_apps_from_address() {
  return "no-reply@skateistan.org";
}

function _webform_skateistan_apps_process_checkboxes($data) {
  $result = "";
  if ($data && $data['value']) {
    $modified = str_replace('_', ' ', $data['value']);
    $result = implode(", ", $modified);
  }
  return $result;
}

function _webform_skateistan_apps_submit_ia($node, $submission) {
  $hook_url = "http://skateistanappreceiver.heroku.com/a/";
  $mapping = _webform_skateistan_apps_webform_component_mapping($node);

  $position = $submission->data[$mapping['position']]['value'][0];
  $name = $submission->data[$mapping['name']]['value'][0];
  $email = $submission->data[$mapping['email']]['value'][0];
  $skills = _webform_skateistan_apps_process_checkboxes($submission->data[$mapping['skills']]);
  if ($submission->data[$mapping['other_skills']]['value']) {
    $skills .= ", " . $submission->data[$mapping['other_skills']]['value'][0];
  }

  $note = "Intern Application: <br /><br />";
  $note .= "Position: " . _webform_skateistan_apps_process_checkboxes($submission->data[$mapping['position']]) . "<br /><br />";
  $note .= "Name: " . $name . "<br /><br />";
  $note .= "Email: " . $email . "<br /><br />";
  $note .= "Address:\n" . $submission->data[$mapping['address']]['value'][0] . "<br /><br />";
  $note .= "Age: " . $submission->data[$mapping['age']]['value'][0] . "<br /><br />";
  $note .= "Sex: " . $submission->data[$mapping['sex']]['value'][0] . "<br /><br />";
  $note .= "Nationality: " . $submission->data[$mapping['nationality_ies']]['value'][0] . "<br /><br />";
  $note .= "Languages: " . $submission->data[$mapping['languages']]['value'][0] . "<br /><br />";
  $note .= "What appeals to you about the Skateistan project?\n" . $submission->data[$mapping['appeals']]['value'][0] . "<br /><br />";
  $note .= "What skills do you have that will help us deliver our programs to young people?\n" . $skills . "<br /><br />";
  $note .= "Have you worked for a small organisation or NGO before?\n" . $submission->data[$mapping['ngo']]['value'][0] . "<br /><br />";
  $note .= "Have you worked with children before?\n" . $submission->data[$mapping['children']]['value'][0] . "<br /><br />";
  $note .= "Have you travelled to developing or Muslim countries before?\n" . $submission->data[$mapping['developing']]['value'][0] . "<br /><br />";
  $note .= "Do you have skateboarding experience? (if yes, how many years and what skill level)\n" . $submission->data[$mapping['skateboarding']]['value'][0] . "<br /><br />";
  $note .= "Do you have ramp building or trade skills?\n" . $submission->data[$mapping['ramp']]['value'][0] . "<br /><br />";
  $note .= "Do you have any medical condition that need to be considered before travelling to a developing country?\n" . $submission->data[$mapping['medical']]['value'][0] . "<br /><br />";
  $note .= "Timeline\n" . $submission->data[$mapping['timeline']]['value'][0] . "<br /><br />";

  $attachments = array();
  foreach ($node->webform['components'] as $component) {
    if ($component['type'] == 'file') { // cv file
      $cv = _webform_skateistan_apps_get_file($submission->data[$component['cid']]['value'][0]);
      if ($cv) $attachments[] = $cv;
    }
  }
  if ($cv) $note .= "Link to CV file: http://skateistan.org/sites/default/files/webform/" . $cv->filename;

  $data = array(
    "name" => $name,
    "email" => $email,
    "note" => $note,
    "skills" => $skills
  );

  // Send the application
  $options = array(
    'headers' => array('Content-Type' => 'application/x-www-form-urlencoded'),
    'method' => 'POST',
    'data' => http_build_query($data)
    );

  $response = drupal_http_request($hook_url, $options);
  $url = $response->data; // Expected to be: https://skateistan.highrisehq.com/people/{id}
  _webform_skateistan_apps_send_ia_hr_email($url, $data, $attachments);
}

function _webform_skateistan_apps_send_ia_hr_email($url, $data, $attachments) {
  $from_address = _webform_skateistan_apps_from_address();
  $to_address = _webform_skateistan_apps_hr_recipients();
  $subject = "Intern Application";
  $message = "Intern Application submitted by " . $data["name"] . ":<br /><br />";
  $message .= "Applicant has been saved in Highrise: " . $url . "<br /><br />";
  $message .= $data["note"] . "\n";
  $params["subject"] = $subject;
  $params["body"] = $message;
  $params['attachments'] = $attachments;
  $message = drupal_mail("webform_skateistan_apps", "ia_hr", $to_address, language_default(), $params, $from_address, $send = TRUE);


}

function _webform_skateistan_apps_submit_rva($node, $submission) {
  $hook_url = 'http://skateistanappreceiver.heroku.com/rva/';
  $mapping = _webform_skateistan_apps_webform_component_mapping($node);
  $name = $submission->data[$mapping['name']]['value'][0];
  $email = $submission->data[$mapping['email']]['value'][0];
  $note = "Remote Volunteer Application: <br /><br />";
  $note .= "Name: " . $name . "<br /><br />";
  $note .= "Email: " . $email . "<br /><br />";
  $note .= "Address:\n" . $submission->data[$mapping['address_or_location']]['value'][0] . "<br /><br />";
  $note .= "Age: " . $submission->data[$mapping['age']]['value'][0] . "<br /><br />";
  $note .= "Are you a skateboarder? " . $submission->data[$mapping['are_you_a_skateboarder']]['value'][0] . "<br /><br />";
  $note .= "Why are you interested in the Skateistan project?\n" . $submission->data[$mapping['interest']]['value'][0] . "<br /><br />";
  $note .= "How could you help Skateistan from your current location?\n" . $submission->data[$mapping['help']]['value'][0] . "<br /><br />";
  $note .= "How many hours a week could you to dedicate to a remote volunteer position?\n" . $submission->data[$mapping['hours']]['value'][0] . "<br /><br />";
  $note .= "How many months could you potentially dedicate to a remote volunteer position?\n" . $submission->data[$mapping['months']]['value'][0] . "\n";

  $data = array(
    "name" => $name,
    "email" => $email,
    "note" => $note
  );
  // Send the application
  $options = array(
    'headers' => array(),
    'method' => 'POST',
    'data' => http_build_query($data)
  );
  $options['headers'] = array(
    'Content-Type' => 'application/x-www-form-urlencoded',
  );

  $response = drupal_http_request($hook_url, $options);
  $url = $response->data; // Expected to be: https://skateistan.highrisehq.com/people/{id}
  _webform_skateistan_apps_send_rva_hr_email($url, $data);
}

function _webform_skateistan_apps_send_rva_hr_email($url, $data) {
  $from_address = _webform_skateistan_apps_from_address();
  $to_address = _webform_skateistan_apps_hr_recipients() . ", erika@skateistan.org";
  $subject = "Remote Volunteer Application";
  $message = "Remote Volunteer Application submitted by " . $data["name"] . ":<br /><br />";
  $message .= "Applicant has been saved in Highrise: " . $url . "<br /><br />";
  $message .= $data["note"] . "\n";
  $params["subject"] = $subject;
  $params["body"] = $message;
  drupal_mail("webform_skateistan_apps", "rva_hr", $to_address, language_default(), $params, $from_address);
}

function webform_skateistan_apps_mail($key, &$message, $params) {
  $message["subject"] = $params["subject"];
  $message["body"][] = $params["body"];
}

function _webform_skateistan_apps_webform_component_mapping($node) {
  $mapping = array();
  $components = $node->webform["components"];
  foreach ($components as $i => $component) {
    $key = $component["form_key"];
    $mapping[$key] = $i;
  }
  return $mapping;
}

function _webform_skateistan_apps_get_file($fid) {
  return $fid ? file_load($fid) : FALSE;
}
